# Site settings
title: My Awesome Site
description: >- # this means to ignore newlines until "baseurl:"
  A brief description of your site.
author: Your Name

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Permalinks
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Paginate settings
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - vendor
  - node_modules

# Google Analytics (replace with your tracking ID)
google_analytics: UA-XXXXXXXX-X

# Disqus (replace with your Disqus shortname)
disqus:
  shortname: your-disqus-shortname

# Social media usernames
twitter_username: your_twitter_username
github_username:  your_github_username

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false

# Configuration for jekyll-feed
feed:
  path: feed.xml

# Configuration for jekyll-sitemap
sitemap:
  changefreq: daily
  priority: 0.7

# Configuration for jekyll-seo-tag
seo:
  type: "website"
  name: "My Awesome Site"
  description: "A brief description of your site."
  url: "https://yourusername.github.io"
  twitter:
    username: your_twitter_username
    card: summary
    image: "https://yourusername.github.io/assets/images/your-image.jpg"
  facebook:
    admins: your_facebook_admins
    app_id: your_facebook_app_id

# Custom variables
custom_var: "value"
